//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Task-3/Input/Input.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Input: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Input()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input"",
    ""maps"": [
        {
            ""name"": ""Spawn"",
            ""id"": ""feba46d6-750b-40b6-8480-b7a135fd7721"",
            ""actions"": [
                {
                    ""name"": ""CreateCoin"",
                    ""type"": ""Button"",
                    ""id"": ""4ce01bc7-d4c8-4fe8-b038-396345a09c91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""288d248b-ebd6-443f-adb0-d9b7f1655acd"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CreateCoin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Spawn
        m_Spawn = asset.FindActionMap("Spawn", throwIfNotFound: true);
        m_Spawn_CreateCoin = m_Spawn.FindAction("CreateCoin", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Spawn
    private readonly InputActionMap m_Spawn;
    private List<ISpawnActions> m_SpawnActionsCallbackInterfaces = new List<ISpawnActions>();
    private readonly InputAction m_Spawn_CreateCoin;
    public struct SpawnActions
    {
        private @Input m_Wrapper;
        public SpawnActions(@Input wrapper) { m_Wrapper = wrapper; }
        public InputAction @CreateCoin => m_Wrapper.m_Spawn_CreateCoin;
        public InputActionMap Get() { return m_Wrapper.m_Spawn; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpawnActions set) { return set.Get(); }
        public void AddCallbacks(ISpawnActions instance)
        {
            if (instance == null || m_Wrapper.m_SpawnActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpawnActionsCallbackInterfaces.Add(instance);
            @CreateCoin.started += instance.OnCreateCoin;
            @CreateCoin.performed += instance.OnCreateCoin;
            @CreateCoin.canceled += instance.OnCreateCoin;
        }

        private void UnregisterCallbacks(ISpawnActions instance)
        {
            @CreateCoin.started -= instance.OnCreateCoin;
            @CreateCoin.performed -= instance.OnCreateCoin;
            @CreateCoin.canceled -= instance.OnCreateCoin;
        }

        public void RemoveCallbacks(ISpawnActions instance)
        {
            if (m_Wrapper.m_SpawnActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpawnActions instance)
        {
            foreach (var item in m_Wrapper.m_SpawnActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpawnActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpawnActions @Spawn => new SpawnActions(this);
    public interface ISpawnActions
    {
        void OnCreateCoin(InputAction.CallbackContext context);
    }
}
